### ISSUE TITLE
Fail to authenticate with JWT

### ISSUE THREAD

**Issue by yongabyte** [CircleCI-Public/Salesforce-sfdx-cli-orb#20]
**Orb Version**
The version number of the orb
2.1.0 and 2.0.0 

**Describe the bug**

Workflows started failing around noon EST.

Workflows with the default `- sfdx/install` flag failed to authenticate to Dev orgs. The reason we found was that 
 the `force:auth:jwt:grant` command is dead on sfdx-cli versioned 7.83 (the current default version). 

**To Reproduce**
In the workflow:
1. uses  the default sfdx install option`- sfdx/install`
1. uses JWT as authentication method
1. see error
```
 ›   Warning: force:auth:jwt:grant is not a sfdx command.
Did you mean auth:jwt:grant? [y/n]: 
```

**Expected behavior**

The workflow will error out on any command in the `run` step if the workflow looks something like this

```yml
jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: x
      - run:
          command: 
            any sfdx cli commands

```

For us it was verify the default user name with `sfdx force:config:set defaultusername=x` and we got following error.

```
ERROR running config:set:  No AuthInfo found for name x
```

**Additional context**

Current workaround is to specify the sfdx-cli version installed with the orb.

```yml
      - sfdx/install:
          version: '7.82.0'
```
