### ISSUE TITLE
Bug: auth not working 

### ISSUE THREAD

**Issue by rondinardo** [CircleCI-Public/Salesforce-sfdx-cli-orb#34]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Orb version

3.0.2

### Current behavior

Trying to upgrade from version 2.1.  Can't get get "auth" to work. 

When `sf config set org-api-version="${API_VERSION}"` is issued, it seems that API_version is null

**What I used in old version** -- I never used to supply apiVersion:
```
      - sfdx/auth:
          defaultusername: $HUB_SFDC_USER
          jwtKey: HUB_SERVER_KEY_HEX
          consumerKey: HUB_CONSUMER_KEY
```

As above, when auth executes `sf config set org-api-version="${API_VERSION}"` I get this error:  

```
Set Config
 Name  Value  Success  Message 
-------------------------------
 org…         false    You mu… 

```
I believe this is because API_VERSION is null.   Unfortunately CircleCI is cutting the message off, but you can see the value is empty.

Then I try 
```

      - sfdx/auth:
          defaultusername: $HUB_SFDC_USER
          jwtKey: HUB_SERVER_KEY_HEX
          consumerKey: HUB_CONSUMER_KEY
          apiVersion: '61.0'
```

I still get the same error where it thinks that `API_VERSION` is empty.  I don't want to supply apiVersion, but it seems it's not smart enough to know I didn't supply it, so it shouldn't need to execute `sf config set org-api-version="${API_VERSION}"` at all.

### Minimum reproduction config

```
version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@3.0.2

commands:
  install-cli:
    steps:
      - sfdx/install:
            version: latest
jobs:
  scratchBuild:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - install-cli
      - sfdx/auth:
          defaultusername: $HUB_SFDC_USER
          jwtKey: HUB_SERVER_KEY_HEX
          consumerKey: HUB_CONSUMER_KEY
          apiVersion: '61.0'
      - sfdx/scratch_create:
          scratch_alias: ${CIRCLE_BRANCH}
          scratch_config: ./config/default-scratch-def.json
      - run:
          name: Build and run all tests
          command: sf project deploy start --source-dir force-app/main --ignore-conflicts --target-org ${CIRCLE_BRANCH} --wait 999 --test-level RunLocalTests
      - sfdx/scratch_delete:
          scratch_alias: ${CIRCLE_BRANCH}

workflows:
  validate:
    jobs:
      - scratchBuild
```

**Comment by rmunozst** [comment]
I tried adding every parameter to the auth command and got a different error...

**Job**
```
      - sfdx/install:
          version: latest
      - sfdx/auth:
          defaultusername: <my username>
          instanceUrl: 'https://<my company>.my.salesforce.com/'
          apiVersion: '62.0'
          jwtKey: SFDX_JWT_KEY
          consumerKey: SFDX_CONSUMER_KEY
          defaultdevhubusername: '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}'
```
**Error output**
```
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.

Set Config
 Na…  Va…  Su… 
---------------
 or…  ht…  tr… 

Error (JwtGrantError): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: JwtAuthError::Error authenticating with JWT.
Errors encountered:
client identifier invalid
client identifier invalid
client identifier invalid
client identifier invalid
client identifier invalid


Exited with code exit status 1
```
Meanwhile, I reran the failed job with SSH and from bash was able to get the exact same sf commands in the [auth.sh](https://github.com/CircleCI-Public/Salesforce-sfdx-cli-orb/blob/master/src/scripts/auth.sh) file to work. This proves it's nothing wrong with my username or server key or consumer key, the typical culprits of the dreaded `client identifier invalid` error.

**Comment by alain-odea-sequence** [comment]
Same issue for me. I'm able to get the auth.sh to work if I supply the env vars to it directly.

I can even get it to work if I copy paste the contents of auth.sh into a config.yml as a run command.

There are several fatal bugs:

1. Attempting to use env_var_name variables without interpreting them (you cannot do `${CONSUMER_KEY}` since the value is literally `SFDX_CONSUMER_KEY`, you need to do `${!CONSUMER_KEY}`)
2. Handing DEFAULT_DEVHUB_USERNAME as the literal string `${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}` and then not interpreting that in auth.sh using envsubstr or similar in auth.sh)
3. Defaulting to API_VERSION "" when that is invalid and will trigger an error

I'm going to attempt a Pull Request to correct these issues.

Here's a working example with the auth command inlined and bugs fixed to run from until that gets done or someone beats me to it:
```
version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@3

commands:
  sfdx_auth:
    parameters:
      defaultusername:
        description: The username for an org that all commands run against by default.
        type: string
      defaultdevhubusername:
        description: The username of your Dev Hub org that the 'org create scratch' command defaults to. Used as alias.
        default: ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
        type: string
      jwtKey:
        description: Environment variable containing the base64 encoded private server key.
        default: SFDX_JWT_KEY
        type: env_var_name
      consumerKey:
        description: "The consumer key of the connected app for salesforce. Stored as an environment variable"
        default: SFDX_CONSUMER_KEY
        type: env_var_name
      instanceUrl:
        description: The URL of the Salesforce instance that is hosting your org.
        default: ""
        type: string
      apiVersion:
        description: The API version for a specific project or all projects. Normally, the Salesforce CLI assumes that you're using the same version of the CLI as the Dev Hub org.
        default: ""
        type: string
      decryption_key:
        description: Environment variable name for server.key decryption key, if available.
        default: DECRYPTION_KEY
        type: env_var_name
      server_key:
        description: Path to encrypted server.key within the project, if available.
        default: ""
        type: string
    steps:
      - checkout
      - sfdx/install
      - when:
          condition:
            not: << parameters.server_key >>
          steps:
            - run:
                name: Check and install SFDC authentication key
                command: |
                  if [ -z $<<parameters.jwtKey>> ]; then
                    echo "Authentication requires a base64 encoded server key to be provided as an environment variable. Please ensure the <<parameters.jwtKey>> env var has been set correctly."
                    exit 1
                  fi
                  if [ -z $<<parameters.consumerKey>> ]; then
                    echo "Authentication requires a consumer key to be present. Please ensure the <<parameters.consumerKey>> env var has been set correctly."
                    exit 1
                  fi
                  echo Creating jwt key file.
                  echo
                  if [ -f ./server.key ]; then
                    echo "It appears you may have committed your server.key file. For your safety please never commit secrets to your code repository. We instead recommend utilizing environment variables for this purpose. You may wish to invalidate and regenerate your server key."
                    exit 1
                  fi
                  echo $<<parameters.jwtKey>> | base64 --decode > ./server.key

      - when:
          condition:
            and: [ << parameters.decryption_key >>, << parameters.server_key >> ]
          steps:
            - run:
                name: Decrypt SFDC authentication key.
                command: |
                  openssl enc -aes-256-cbc -md sha256 -salt -d -in << parameters.server_key >> -out server.key -K << parameters.decryption_key >> -pbkdf2

      - run:
          name: Authenticate with Salesforce
          environment:
            INSTANCE_URL: <<parameters.instanceUrl>>
            CONSUMER_KEY: <<parameters.consumerKey>>
            DEFAULT_USERNAME: <<parameters.defaultusername>>
            DEFAULT_DEVHUB_USERNAME: <<parameters.defaultdevhubusername>>
            API_VERSION: <<parameters.apiVersion>>
          command: >
            #! /bin/bash -x
            
            sf config set org-instance-url="${INSTANCE_URL}" --global
            
            sf auth jwt grant \
                --client-id "${!CONSUMER_KEY}" \
                --jwt-key-file ./server.key \
                --username "${DEFAULT_USERNAME}" \
                --instance-url "${INSTANCE_URL}" \
                --set-default-dev-hub \
                --alias "$(echo "${DEFAULT_DEVHUB_USERNAME}" | envsubst)"
            
            sf config set org-api-version="${API_VERSION}"

jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - sfdx_auth:
          instanceUrl: https://YOUR DEV ORG INSTANCE URL HERE
          defaultusername: your-username@yourdomain.example.com
          apiVersion: "64.0"
      - run:
          command: >
            echo You now have access to the sf cli and may execute commands
            against it.

            sf auth list
          name: Run your SF commands here

workflows:
  basic-test:
    jobs:
      - install_authenticate
```
